import type { Metadata } from "next";
import {  Chakra_Petch } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import ClientProviders from "@/providers/ClientProviders";




const chakra = Chakra_Petch({
  variable: "--font-chakra-petch",
  subsets: ["latin"],
  weight: ["300","400","500","600","700"],
  style: "normal"
});



export const metadata: Metadata = {
  title: "Digidrop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${chakra.variable} antialiased bg-[#1C1C1C]`}
      >
        <Toaster position="bottom-right" richColors/>
        <ClientProviders>
           {children}
        </ClientProviders>
        
      </body>
    </html>
  );
}
